version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: cclmonitor
    main: ./cmd/cclmonitor
    binary: cclmonitor
    env:
      - CGO_ENABLED=0
    goos: [darwin, linux, windows]
    goarch: [amd64, arm64]
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: cclmonitor-install
    main: ./cmd/cclmonitor-install
    binary: cclmonitor-install
    env:
      - CGO_ENABLED=0
    goos: [darwin, linux, windows]
    goarch: [amd64, arm64]
    ignore:
      - goos: windows
        goarch: arm64

  - id: cclmonitor-ui
    main: ./cmd/cclmonitor-ui
    binary: cclmonitor-ui
    env:
      - CGO_ENABLED=0
    goos: [darwin, linux, windows]
    goarch: [amd64, arm64]
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - ids: [cclmonitor, cclmonitor-install, cclmonitor-ui]
    name_template: "cclmonitor_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^Merge "
